# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
target 'DcentBiometricSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DcentBiometricSample
  pod 'SwiftProtobuf'
  pod 'BigInt', '~> 5.0'
  
  target 'DcentBiometricSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
